seperator = '^&^'

[darwin-amd64]
command = [ 'sudo^&^installer^&^-pkg^&^{{.DlFileName}}^&^-target^&^{{.InstallDir}}' ]
comment = [ 'Installing Go version {{printf "%s\n" .NewVersion}}' ]
extension = 'pkg'
installdir = '/'

[darwin-arm64]
command = [ 'sudo^&^installer^&^-pkg^&^{{.DlFileName}}^&^-target^&^{{.InstallDir}}' ]
comment = [ 'Installing Go version {{printf "%s\n" .NewVersion}}' ]
extension = 'pkg'
installdir = '/'

[darwin-armv6l]
command = [ 'sudo^&^installer^&^-pkg^&^{{.DlFileName}}^&^-target^&^{{.InstallDir}}' ]
comment = [ 'Installing Go version {{printf "%s\n" .NewVersion}}' ]
extension = 'pkg'
installdir = '/'

[linux-amd64]
command = [ 'sudo^&^rm^&^-rf^&^{{.InstallDir}}/go', 'sudo^&^tar^&^-C^&^{{.InstallDir}}^&^-xvf^&^{{.TempDir}}/{{.DlFileName}}' ]
comment = [ 'Removing Go version {{printf "%s\n" .CurVersion}}', 'Installing Go version {{printf "%s\n" .NewVersion}}' ]
extension = 'tar.gz'
installdir = '/usr/local'

[linux-arm64]
command = [ 'sudo^&^rm^&^-rf^&^{{.InstallDir}}/go', 'sudo^&^tar^&^-C^&^{{.InstallDir}}^&^-xvf^&^{{.TempDir}}/{{.DlFileName}}' ]
comment = [ 'Removing Go version {{printf "%s\n" .CurVersion}}', 'Installing Go version {{printf "%s\n" .NewVersion}}' ]
extension = 'tar.gz'
installdir = '/usr/local'

[windows-386]
command = [ 'msiexec^&^/i^&^{{.TempDir}}\{{.DlFileName}}' ]
comment = [ 'Installing Go version {{printf "%s\n" .NewVersion}}' ]
extension = 'msi'
installdir = 'C:\Program Files (x86)\Go'

[windows-amd64]
command = [ 'msiexec^&^/i^&^{{.TempDir}}\{{.DlFileName}}' ]
comment = [ 'Installing Go version {{printf "%s\n" .NewVersion}}' ]
extension = 'msi'
installdir = 'C:\Program Files\Go'
